services:
  - type: web
    name: homework-platform
    env: python
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: 
      - python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: 'your_secret_key_here'
      - key: UPLOAD_FOLDER
        value: 'uploads'
      - key: DATABASE_URL
        value: 'sqlite:///homework_platform.db'
    staticPublishPath: static
    autoDeploy: true
    disk:
      - mountPath: /persistent/uploads
        sizeGB: 1
