"""Initial migration

Revision ID: a66fef34be0f
Revises: 
Create Date: 2024-09-27 18:31:06.944093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66fef34be0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_index('ix_homework_timestamp')

    op.drop_table('homework')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('cost', sa.FLOAT(), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.create_index('ix_homework_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
